# Generated by Django 3.2 on 2021-09-04 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='attack',
            field=models.IntegerField(default=1, verbose_name='攻击力'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='defend',
            field=models.IntegerField(default=1, verbose_name='防御力'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monster',
            name='attack',
            field=models.IntegerField(default=1, verbose_name='攻击力'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monster',
            name='defend',
            field=models.IntegerField(default=1, verbose_name='防御力'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='sync',
            field=models.IntegerField(verbose_name='体力'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='sync',
            field=models.IntegerField(verbose_name='体力'),
        ),
        migrations.CreateModel(
            name='ArmorArms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='装备名称')),
                ('summary', models.TextField(verbose_name='装备描述')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/armor/%Y/%m/%d/', verbose_name='封面')),
                ('slot', models.IntegerField(verbose_name='装备槽位')),
                ('behavior', models.TextField(verbose_name='单位行为')),
                ('behavior_script', models.TextField(blank=True, null=True, verbose_name='单位行为代码')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('delete_flag', models.SmallIntegerField(default=0, verbose_name='删除标记')),
                ('editor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='编辑人')),
            ],
            options={
                'verbose_name': '装备',
            },
        ),
    ]
