# Generated by Django 3.2.4 on 2021-06-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simc', '0005_auto_20210618_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlefield',
            name='card',
            field=models.TextField(blank=True, verbose_name='卡牌列表'),
        ),
        migrations.AlterField(
            model_name='battlefield',
            name='character',
            field=models.TextField(blank=True, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='battlefield',
            name='loop',
            field=models.TextField(blank=True, verbose_name='模拟次数'),
        ),
        migrations.AlterField(
            model_name='battlefield',
            name='monster',
            field=models.TextField(blank=True, verbose_name='怪物列表'),
        ),
    ]
